version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      python-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      github-actions:
        patterns:
          - "*"
