name: "5. Release SRS"

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pack-and-ship:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
      
      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: � Install Dependencies
        run: pip install -r requirements.txt

      - name: 🚀 Run Release Script
        env:
          GH_TOKEN: ${{ github.token }}
          PYTHONPATH: ${{ github.workspace }}/scripts
        run: python scripts/release_handler.py
